---
- name: check if database for Ianseo exists
  command: mysql -e 'SHOW DATABASES LIKE "{{ ianseobox_ianseo_db }}"' -sN
  register: ianseo_db_exists
  failed_when: ianseo_db_exists.rc > 1
  changed_when: ianseo_db_exists.rc == 0

- name: drop database for Ianseo
  mysql_db:
    name: '{{ ianseobox_ianseo_db }}'
    state: 'absent'
  when: ianseo_db_exists is changed

- name: remove temporary storage for Ianseo cache
  mount:
    name: '{{ item.name }}'
    state: 'unmounted'
  with_items:
    - { name: '/var/cache/ianseo' }
    - { name: '{{ ianseobox_ianseo_data_dir }}/temp' }
    - { name: '{{ ianseobox_ianseo_data_dir }}/sessions' }

- name: remove previous Ianseo installation data
  file:
    path: '{{ item }}'
    state: 'absent'
  with_items:
    - '{{ ianseobox_ianseo_data_dir }}'
    - '{{ ianseobox_ianseo_source_dir }}/config.php'
    - '/var/cache/ianseo'
    - '/var/cache/ianseo-cache-backup'

- name: check if any incron job exist
  shell: 'incrontab -l | wc -c'
  register: incronjob_exists
  changed_when: incronjob_exists.stdout|int > 0

- name: remove incron jobs
  command: 'incrontab -u root -r'
  when: incronjob_exists is changed
