---
- name: format release date using locales
  command: "date --date={{ ianseobox_release_date }} '+%-d %B %Y'"
  environment:
    - LC_ALL: '{{ item.1 }}'
  with_indexed_items: '{{ ianseobox_locales }}'
  register: 'formatted_dates'
  when: 'formatted_dates is not defined or item.0 < ianseobox_locales|length'

- name: set vars with formatted dates
  set_fact: '{{ item.0 | regex_replace("^(.*)_.*UTF-8$", "ianseobox_release_date_\1") }}={{ item.1.stdout }}'
  with_together:
    - '{{ ianseobox_locales }}'
    - '{{ formatted_dates.results }}'

- name: set summary string with formatted dates
  set_fact:
    ianseobox_ianseo_summary: '{{ ianseobox_ianseo_summary }}'
